### ISSUE TITLE
I have an Error

### ISSUE THREAD

**Issue by bjkim07** [hideakitai/obsidian-vim-im-control#4]
I don't know why I have this error. 

I have an Error below
```
Error: Command failed: im-select
/bin/sh: im-select: command not found
, stdout: , stderr: /bin/sh: im-select: command not found

logError @ plugin:vim-im-control:248
```
My current Setting is below and my vault is in the icloud folder. 
<img width="623" alt="Screen Shot 2024-07-28 at 10 04 26" src="https://github.com/user-attachments/assets/9da4d2f5-0e8f-4777-9b6b-1038092617f5">

Thanks for your support

**Comment by hideakitai** [comment]
Do you have im-select installed? If you haven't, [please install it](https://github.com/daipeihust/im-select?tab=readme-ov-file#install).

```
brew install im-select
```

Please confirm where `im-select` is if you have already installed it.

```
which im-select
```

Please copy and paste the path to `PATH to IM Controller`.

**Comment by bjkim07** [comment]
I already installed im-select

```
 >>> % which im-select
/usr/local/bin/im-select
```
and I also did copy and paste the path to PATH to IM controller as my previous screenshot. 

Thank you for your help.

**Comment by hideakitai** [comment]
Ah, sorry.

> Please copy and paste the path to PATH to IM Controller.

This sentence means to paste the `/usr/local/bin/` instead of `/usr/local/bin/im-select`. `PATH` means the directory (folder) where the `im-select` is placed.

Please refer to the README for example settings.

https://github.com/hideakitai/obsidian-vim-im-control

**Comment by bjkim07** [comment]
I already set the PATH in the obsidian preference. 
but there is still a problem, how can I fix it? 
is there any problem for obsidian to gain an access to the usr/local/bin folder? 

I really appreciate for your help.  

![Screen Shot 2024-07-31 at 08 30 07](https://github.com/user-attachments/assets/c0facb6f-5635-4d27-b3a0-d5e78dd4bfbb)

**Comment by hideakitai** [comment]
Hm... as you mentioned, Obsidian couldn't find the executable (`/usr/local/bin/im-select`). In my macOS with the latest Obsidian, it works correctly. The difference is that the `PATH` is not the same as yours (`/opt/homebrew/bin`).

So, please 

1. Take a screenshot of the terminal after you run these commands

```
which im-select
```

then

```
im-select
```

2. Please try to remove `/` from the end of the `PATH` (`/usr/local/bin/` -> `/usr/local/bin`)

**Comment by bjkim07** [comment]
I deleted "/" in the end of the PATH but there is still the same error.

and this is a screenshot below. 

![Screen Shot 2024-07-31 at 08 50 04](https://github.com/user-attachments/assets/c4b08f6a-de44-4227-94e6-421c410b8000)

**Comment by hideakitai** [comment]
It's a strange behavior. Please send me your Mac version and Obsidian's version.

**Comment by bjkim07** [comment]
Obsidian version is below. 
```
About Obsidian
Version 1.6.7 (Installer 1.4.13)
```
and Mac version is below
![Screen Shot 2024-07-31 at 08 56 02](https://github.com/user-attachments/assets/61c76f5f-3250-4536-91ba-1835206b53ec)

**Comment by hideakitai** [comment]
Ok. Then please try 2 things.

Please send me a log of the Obsidian

  1. Launch Obsidian
  2. Press Cmd + Shift + `i`
  3. You can see the Developer Tool (maybe) in the right side of your obsidian
  4. Select `Console` tab
  5. Restart your Obsidian
  6. Make some actions (open file, enter insert mode, write text, leave insert mode, etc.)
  7. Please take a screen shot
  8. Also copy the all logs and paste here

![image](https://github.com/user-attachments/assets/8a414bdb-45ca-455c-9bbe-b1e433c4918c)

**Comment by hideakitai** [comment]
Please re-install Obsidian

**Comment by bjkim07** [comment]
wow. It fixed. I don't know why. But after relaunch, suddenly it works well. 

and there is no error log in the console message, now. 

Thank you for your support and sharing this good plug-in.

Have a nice day, and Stay healthy and well during the hot summer.
